---
- name: Install basic packeges
  apt:
    name: "{{ item }}"
    update_cache: yes
    autoremove: yes
  with_items:
    - iotop
    - libpq-dev
  when: ansible_os_family == "Debian"

- name: Install psycopg2
  pip:
    name: psycopg2
    state: latest